# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'memeGrave' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memeGrave
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'  
  pod 'SwiftLint'
  pod 'CBFlashyTabBarController'

  target 'memeGraveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memeGraveUITests' do
    # Pods for testing
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9'
    end
  end
end

end
