# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'memeGrave' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memeGrave
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Google'  


  target 'memeGraveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memeGraveUITests' do
    # Pods for testing
  end

end
